const lifeQuotes = [
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { text: "Breathe in the future, breathe out the past.", author: "Unknown" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { text: "Every moment is a fresh beginning.", author: "T.S. Eliot" },
    { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
    { text: "Keep looking up... that's the secret of life.", author: "Snoopy" },
    { text: "What we think, we become.", author: "Buddha" },
    { text: "Happiness is not by chance, but by choice.", author: "Jim Rohn" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Look closely. The beautiful may be small.", author: "Immanuel Kant" },
    { text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Embrace the glorious mess that you are.", author: "Elizabeth Gilbert" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "You are enough just as you are.", author: "Meghan Markle" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
    { text: "Let beauty be what you do.", author: "Rumi" },
    { text: "Make each day your masterpiece.", author: "John Wooden" },
    { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
    { text: "There is no path to happiness. Happiness is the path.", author: "Thich Nhat Hanh" },
    { text: "Change the world by being yourself.", author: "Amy Poehler" },
    { text: "To live will be an awfully big adventure.", author: "J.M. Barrie" },
    { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
    { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "Let it hurt, then let it go.", author: "r.h. Sin" },
    { text: "May your choices reflect your hopes, not your fears.", author: "Nelson Mandela" },
    { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
    { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "Life is a flower of which love is the honey.", author: "Victor Hugo" },
    { text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain" },
    { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
    { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
    { text: "Every day brings a chance for you to draw in a breath, kick off your shoes, and dance.", author: "Oprah Winfrey" },
    { text: "No matter what people tell you, words and ideas can change the world.", author: "Robin Williams" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
    { text: "When words fail, music speaks.", author: "Hans Christian Andersen" },
    { text: "Sometimes you will never know the value of a moment, until it becomes a memory.", author: "Dr. Seuss" },
    { text: "Find out who you are and do it on purpose.", author: "Dolly Parton" },
    { text: "Quiet people have the loudest minds.", author: "Stephen Hawking" },
    { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
    { text: "Normality is a paved road: it's comfortable to walk, but no flowers grow on it.", author: "Vincent van Gogh" },
    { text: "The most wasted of days is one without laughter.", author: "E.E. Cummings" },
    { text: "Light tomorrow with today.", author: "Elizabeth Barrett Browning" },
    { text: "What you get by achieving your goals is not as important as what you become.", author: "Zig Ziglar" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "You do not find the happy life. You make it.", author: "Camilla Eyring Kimball" },
    { text: "Once you replace negative thoughts with positive ones, you'll start having positive results.", author: "Willie Nelson" },
    { text: "Yesterday is not ours to recover, but tomorrow is ours to win or lose.", author: "Lyndon B. Johnson" },
    { text: "Only I can change my life. No one can do it for me.", author: "Carol Burnett" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "You learn more from failure than from success.", author: "Unknown" },
    { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
    { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Limit your 'always' and your 'nevers'.", author: "Amy Poehler" },
    { text: "Nothing is impossible. The word itself says 'I'm possible!'", author: "Audrey Hepburn" },
    { text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill" },
    { text: "Let us make our future now, and let us make our dreams tomorrow's reality.", author: "Malala Yousafzai" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "Peace begins with a smile.", author: "Mother Teresa" },
    { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone" },
    { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
    { text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
    { text: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
    { text: "Take rest; a field that has rested gives a bountiful crop.", author: "Ovid" },
    { text: "A happy soul is the best shield for a cruel world.", author: "Atticus" },
    { text: "Worrying is like paying a debt you don't owe.", author: "Mark Twain" },
    { text: "The little things in life are the happiest.", author: "Unknown" },
    { text: "Don't seek, don't search, don't ask, don't knock, don't demand – relax.", author: "Osho" },
    { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
    { text: "You can't cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
    { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { text: "The creation of a thousand forests is in one acorn.", author: "Ralph Waldo Emerson" }
];
